# Chinese translations for PROJECT.
# Copyright (C) 2022 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2022.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2022-12-01 10:37+0800\n"
"PO-Revision-Date: 2022-11-25 15:42+0800\n"
"Last-Translator: \n"
"Language: zh\n"
"Language-Team: zh <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.10.3\n"

#: /root/WorkCode/kweaver/builder/celery_task/celery_blue.py:230
msgid "{} start running success."
msgstr "{} 成功开始运行。"

#: /root/WorkCode/kweaver/builder/celery_task/celery_blue.py:333
msgid "delete task success"
msgstr "删除任务成功。"

#: /root/WorkCode/kweaver/builder/celery_task/celery_blue.py:454
msgid "stop task success."
msgstr "终止任务成功。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:9
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:21
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:27
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:39
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:51
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:75
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:81
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:99
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:117
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:135
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:141
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:159
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:165
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:9
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:21
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:27
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:51
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:63
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:75
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:87
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:93
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:105
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:111
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:159
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:171
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:177
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:189
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:201
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:213
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:225
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:231
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:16
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:22
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:28
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:70
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:76
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:83
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:89
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:96
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:102
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:109
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:115
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:140
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:146
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:153
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:159
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:165
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:177
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:190
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:196
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:216
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:222
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:228
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:236
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:242
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:249
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:255
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:274
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:288
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:294
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:301
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:307
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:368
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:374
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:9
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:15
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:21
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:27
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:40
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:46
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:52
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:58
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:76
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:82
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:88
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:94
msgid "Please check your parameter again."
msgstr "请重新检查输入参数。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:15
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:33
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:45
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:87
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:93
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:105
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:111
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:129
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:147
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:153
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:171
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:15
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:57
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:81
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:99
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:123
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:147
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:165
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:183
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:195
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:207
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:219
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:237
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:9
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:15
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:47
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:53
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:59
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:65
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:71
msgid "Please contact the developers."
msgstr "请联系开发人员"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:19
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:20
msgid "task_id [task_id] not exists."
msgstr "任务id [task_id] 不存在。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:37
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:38
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:139
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:140
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:163
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:164
msgid "graph id [graph_id] not exists."
msgstr "图谱id [graph_id] 不存在。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:49
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:50
msgid "subgraph id [subgraph_id] not exists."
msgstr "子图id [subgraph_id] 不存在。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:55
msgid "task cannot run, the storage address of this graph does not exist."
msgstr "任务不可运行，图数据库地址不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:56
msgid "invalid storage address."
msgstr "无效的存储地址"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:57
msgid "Please config a valid graph_db address for this graph."
msgstr "请重新配置图数据库。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:61
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:62
msgid "task cannot run, the current knowledge graph has not been configured yet."
msgstr "任务不可运行，当前图谱尚未完成配置"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:63
msgid "Please try again after configuration."
msgstr "请在配置结束后重试"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:67
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:68
msgid "task cannot run, the current knowledge graph is running or waiting."
msgstr "任务不可运行，当前图谱状态为待运行或运行中"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:69
msgid "Please try again after the task ends."
msgstr "请在任务结束后重试"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:73
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:74
msgid "task id must be integer."
msgstr "任务id必须为正整数"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:79
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:80
msgid "task id [task_id] not exists."
msgstr "任务id [task_id] 不存在。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:115
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:116
msgid "task not exists. "
msgstr "任务不存在。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:121
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:122
msgid "task cannot stop, because the task status is not waiting or running."
msgstr "任务不在运行在或等待中，无法终止。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/celery_error.py:123
msgid "you cannot stop a completed graph task."
msgstr "不能终止已结束的任务。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:8
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:115
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:127
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:133
msgid "Parameter [arg] Error."
msgstr "参数[arg]错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:14
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:56
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:80
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:98
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:122
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:146
msgid "[cause]"
msgstr "[cause]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:19
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:20
msgid "graphid [graphid] not exists."
msgstr "graphid [graphid] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:25
msgid "key type error"
msgstr "key类型错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:26
msgid "key should be list of string"
msgstr "key应为字符串列表"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:31
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:32
msgid "graphdb id [graphdb_id] not exists"
msgstr "图数据库id [graphdb_id] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:33
msgid "please config your graphdb again."
msgstr "请重新配置图数据库"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:43
msgid "these keys are not supported: [unsupported_key]"
msgstr "这些字段不支持: [unsupported_key]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:44
msgid "some keys are not supported."
msgstr "key中有不支持的字段"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:45
msgid "please check your parameter key again."
msgstr "请检查传入的参数key"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:50
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:74
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:92
msgid "argument [arg] error"
msgstr "参数[arg]错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:61
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:62
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:85
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:86
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:103
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:104
msgid "graph id [graphid] not exists"
msgstr "graph id [graphid] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:67
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:68
msgid "ontology id [otl_id] not exists"
msgstr "本体id [otl_id] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:69
msgid "Please config the ontology."
msgstr "请配置本体"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:109
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:110
msgid "[class_type] [name] not exists"
msgstr "[class_type] [name] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:116
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:128
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:134
msgid "parameter [arg] not exists or invalid"
msgstr "参数 [arg] 不存在或者非法"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:117
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:129
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:135
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:141
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:153
msgid "please ensure parameter [arg] exists and valid"
msgstr "请检查传入的参数 [arg]。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:139
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:140
msgid "Parameter [arg] too big please lower than [max]"
msgstr "参数 [arg] 太大, 请选择小于 [max]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:151
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:152
msgid "Parameter [arg] not allow, please choose [allowed]"
msgstr "参数 [arg] 不被允许, 请选择 [allowed]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:175
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:176
msgid "graph id [graph_id] not exists"
msgstr "图谱id [graph_id] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:229
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:230
msgid "knowledge network id [knw_id] not exists"
msgstr "知识网络 [knw_id] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graph_error.py:243
msgid ""
"Please check whether you have permission to delete or whther the graph is"
" running."
msgstr "请检查你是否有权限删除或图谱是否在运行中"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graphdb_error.py:9
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graphdb_error.py:33
msgid "Please check whether the OrientDB request information is correct."
msgstr "请检查OrientDB请求信息是否正确"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graphdb_error.py:15
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graphdb_error.py:39
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graphdb_error.py:45
msgid "Please check whether the Nebula request information is correct."
msgstr "请检查Nebula请求信息是否正确"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graphdb_error.py:21
msgid "Please check whether your GraphDB service is running normally."
msgstr "请检查图数据库服务是否正常运行"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/graphdb_error.py:27
msgid "Please check whether your DB name is correct."
msgstr "请检查图数据库名称是否正确"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:19
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:20
msgid "knowledge graph is waiting build, please calculate after building"
msgstr "知识图谱在等待运行中，构建完成后可进行计算。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:21
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:27
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:33
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:41
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:77
msgid "Please check graph status"
msgstr "请检查图谱状态"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:25
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:26
msgid "knowledge graph is building, please calculate after building"
msgstr "知识图谱正在运行中，构建完成后可进行计算。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:31
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:32
msgid "knowledge graph is configuring build, please calculate after building"
msgstr "知识图谱正在配置中，构建完成后可进行计算。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:37
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:39
msgid ""
"knowledge graph store in NebulaGraph, if you need intelligence score, "
"please calculate after building successfully"
msgstr "由于知识图谱存储于nebula数据库中，若需计算，请先将图谱构建成功。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:45
msgid "call async task service error"
msgstr "调用异步任务服务错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:46
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:52
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:58
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:64
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:70
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/network_error.py:8
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/network_error.py:14
msgid "[detail]"
msgstr "[detail]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:51
msgid "async task service internal error"
msgstr "异步任务服务内部错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:57
msgid "cancel async task service internal error"
msgstr "异步任务服务内部错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:63
msgid "graph intelligence info query error"
msgstr "图谱智商信息查询错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:69
msgid "network intelligence info query error"
msgstr "知识网络智商信息查询错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:75
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:76
msgid ""
"Knowledge graph status invalid, please calculate after building "
"successfully"
msgstr "知识图谱构建状态非法, 请构建后再计算"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:81
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:82
msgid "knowledge network [knw_id] not exists"
msgstr "知识网络 [knw_id] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:83
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:89
msgid "please config your knowledge network again."
msgstr "请重新配置图数据库"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:87
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/intelligence_error.py:88
msgid "knowledge graph [graph_id] not exists"
msgstr "知识图谱 [graph_id] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:9
msgid "Please check the database connection."
msgstr "请检查数据库连接情况"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:21
msgid ""
"The specified knowledge_id [knowledge_id] does not exist, lexicon "
"creation failed!"
msgstr "指定的知识网络id [knowledge_id] 不存在，词库创建失败"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:27
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:227
msgid ""
"Lexicon name [lexicon_name] already exists and cannot be created "
"repeatedly."
msgstr "词库名称 [lexicon_name] 已经存在，不可以重复创建"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:33
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:312
msgid "[ErrorDetails]"
msgstr "[ErrorDetails]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:34
msgid "Please check the type, size and content format of the uploaded file."
msgstr "请核对上传文件的大小、类型以及内容格式"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:39
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:324
msgid "Only one file can be selected at most."
msgstr "仅支持上传一个文件"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:40
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:46
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:325
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:331
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:349
msgid "Please select upload file again."
msgstr "请重新选择上传文件"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:45
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:330
msgid "The file format only supports txt and CSV."
msgstr "文件格式错误，仅支持txt、csv"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:51
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:336
msgid "File content format error."
msgstr "文件内容格式错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:52
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:337
msgid ""
"Please check the content and format of the document according to the "
"template."
msgstr "请按照模板核对文件内容格式"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:57
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:342
msgid "The file only supports UTF-8 encoding."
msgstr "上传文件只支持UTF-8编码"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:58
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:343
msgid "Please confirm the file code and reselect the file."
msgstr "请确认文件编码，重新选择文件"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:63
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:354
msgid "The amount of uploaded file data exceeds."
msgstr "上传文件数据量超出"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:64
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:355
msgid ""
"The uploaded file must be less than 10M and the number of lines must be "
"less than 350000."
msgstr "文件大小不可超过10M，且在35万行以内"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:75
msgid ""
"The specified knowledge_id [knowledge_id] does not exist, get labels "
"failed!"
msgstr "指定的知识网络id [knowledge_id] 不存在，获取标签失败"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:88
msgid ""
"The specified knowledge_id [knowledge_id] does not exist, get lexicon "
"failed!"
msgstr "指定的知识网络id [knowledge_id] 不存在，获取词库信息失败"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:101
msgid "The specified lexicon id [lexicon_id] does not exist, get lexicon failed!"
msgstr "指定的词库id [lexicon_id] 不存在，获取词库信息失败"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:114
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:139
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:158
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:195
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:221
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:241
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:254
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:293
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:306
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:373
msgid "The specified lexicon id [lexicon_id] does not exist."
msgstr "指定的词库id [lexicon_id] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:120
msgid "The format of the new data [data] does not match the original data"
msgstr "新数据 [data] 和词库中已有数据的格式不匹配"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:121
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:127
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:171
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:202
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:319
msgid "Please check lexicon format again."
msgstr "请重新检查输入参数"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:126
msgid "The newly added word [data] already exists."
msgstr "新增的词汇[data]已经存在."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:132
msgid "lexicon [lexicon_id] status is running, cannot insert."
msgstr "running状态的词库[lexicon_id]，无法新增词汇"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:133
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:183
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:208
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:267
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:361
msgid "lexicon status is running, please make sure lexicon status is correct."
msgstr "词库状态running，请确保词库状态正确"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:164
msgid "The specified lexicon word [lexicon_word] does not exist."
msgstr "指定的词库词汇 [lexicon_word] 不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:170
msgid "New data [new_info] and original data [old_info] fields are inconsistent."
msgstr "新数据 [new_info] 和 已有数据 [old_info] 的字段不一致"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:176
msgid "The modified word [lexicon_word] already exists."
msgstr "修改后的词汇[lexicon_word]已经存在."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:182
msgid "lexicon [lexicon_id] status is running, cannot edit word."
msgstr "running状态的词库[lexicon_id]，无法编辑词汇"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:201
msgid "There is no deleted data [delete_data] in the specified lexicon."
msgstr "需要删除的词 [delete_data] 在指定的词库中不存在"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:207
msgid "lexicon [lexicon_id] status is running, cannot delete word."
msgstr "running状态的词库[lexicon_id]，无法删除词汇"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:266
msgid "lexicon [lexicon_id] status is running, cannot export."
msgstr "running状态的词库[lexicon_id]，无法导出"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:280
msgid "Please see the error prompt for details."
msgstr "请查看详细的错误提示信息"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:313
msgid "Please check the type and size of the uploaded file."
msgstr "请核对上传文件的大小、类型以及内容格式"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:318
msgid "New data and original data fields are inconsistent"
msgstr "导入的数据和词库已有数据字段不一致"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:348
msgid "Select at least one file."
msgstr "请至少选择一个文件"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/lexicon_error.py:360
msgid "lexicon [lexicon_id] status is running, cannot import words."
msgstr "running状态的词库[lexicon_id]，无法导入词汇"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/network_error.py:7
msgid "Parameters Error!"
msgstr "参数错误"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/network_error.py:9
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/network_error.py:15
msgid "Please check your parameters."
msgstr "请重新检查输入参数"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/network_error.py:13
msgid "[description]"
msgstr "[description]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:7
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:8
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:38
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:39
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:80
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:81
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:92
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:93
msgid "graph_id [graph_id] not exists."
msgstr "graphid [graph_id] 不存在."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:13
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:14
msgid "ontology_id [ontology_id] not exists."
msgstr "本体id [ontology_id] 不存在."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:19
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:20
msgid "subgraph name [name] already exists."
msgstr "子图名称 [name] 已存在."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:25
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:56
msgid "there are entity classes or edge classes not in the ontology. "
msgstr "有实体类或边类不在本体中。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:31
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:62
msgid "graph is running or waiting."
msgstr "图谱正在运行中或等待中。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:32
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:63
msgid "graph is running or waiting"
msgstr "图谱正在运行中或等待中。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:33
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:64
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:100
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:106
msgid "Please stop building graph or wait the graph finish building."
msgstr "请等待图谱构建成功或停止构建。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:44
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:45
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:86
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:87
msgid "subgraph_id [subgraph_id] not exists."
msgstr "子图 [subgraph_id] 不存在."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:50
msgid "subgraph name already exists."
msgstr "子图名称 [name] 已存在."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:51
msgid "names of these subgraphs are duplicate: [items]"
msgstr "这些子图的名字有重复项：[items]"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:68
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:69
msgid "ungrouped subgraph [subgraph_id] cannot rename."
msgstr "未分组的子图 [subgraph_id] 不能重命名."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:70
msgid "you cannot rename ungrouped."
msgstr "不能对未分组重命名。"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:74
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:75
msgid "subgraph [subgraph_id] name cannot be 未分组 or ungrouped. "
msgstr "子图 [subgraph_id] 的名称不能为 未分组 或 ungrouped."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:98
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:99
msgid "graph status is running, cannot delete subgraph."
msgstr "图谱状态为运行中，无法删除子图 [subgraph_id]."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:104
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:105
msgid "graph status is waiting, cannot delete subgraph."
msgstr "图谱状态为待构建，无法删除子图 [subgraph_id]."

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:110
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:111
msgid "cannot delete ungrouped subgraph [subgraph_id]."
msgstr "不可删除未分组的子图"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:112
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:118
msgid "Please change the subgraph to delete."
msgstr "请更换要删除的子图"

#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:116
#: /root/WorkCode/kweaver/builder/common/errorcode/errors/subgraph_error.py:117
msgid "subgraph_id [subgraph_id] does not exist or does not match the graph_id."
msgstr "子图 [subgraph_id] 不存在或与图谱id不符合."

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:133
msgid "The parameter graph_id must be int!"
msgstr "参数 graph_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:189
#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:271
msgid "The parameter graph_id type must be int!"
msgstr "参数 graph_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:323
msgid "parameters cannot be both graph_id and task_id."
msgstr "参数不能同时为 graph_id 和 task_id 。"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:328
msgid "graph_id must be int."
msgstr "graph_id 必须为正整数"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:332
msgid "graph_id must be larger than zero."
msgstr "graph_id必须大于0."

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:337
msgid "task_id must be int."
msgstr "任务id必须为正整数"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:341
msgid "task_id must be larger than zero."
msgstr "任务id必须为正整数"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:345
msgid "parameter must be graph_id or task_id."
msgstr "参数必须为 graph_id 或 task_id。"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:467
msgid "parameter task_id must be int!"
msgstr "任务id必须为正整数"

#: /root/WorkCode/kweaver/builder/controller/celery_controller.py:471
msgid "parameter task_id cannot be 0!"
msgstr "参数 task_id 不能为0."

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1279
msgid "parameter graph_id must be int!"
msgstr "参数 graph_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1366
msgid "parameter subgraph_id must be int!"
msgstr "参数 subgraph_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1370
msgid "parameter subgraph_id cannot be 0!"
msgstr "参数 subgraph_id 不能为0."

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1406
msgid "parameter graph_id cannot be empty. "
msgstr "参数 graph_id 不能为空。"

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1410
msgid "parameter graph_id must be integer. "
msgstr "graph_id必须为正整数"

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1414
msgid "parameter graph_id must be larger than zero. "
msgstr "参数 graph_id 必须大于0."

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1418
msgid "parameter subgraph_ids cannot be empty. "
msgstr "参数 subgraph_ids不能为空。"

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1422
msgid "parameter subgraph_ids must be a list. "
msgstr "参数 subgraph_ids 必须为列表。"

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1428
msgid "parameter subgraph_id {} must be int!"
msgstr "参数 subgraph_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/controller/graph_controller.py:1432
msgid "parameter subgraph_id must be larger than zero!"
msgstr "参数 subgraph_id 必须大于0."

#: /root/WorkCode/kweaver/builder/service/subgraph_service.py:52
#: /root/WorkCode/kweaver/builder/service/subgraph_service.py:118
msgid "entity {} not in the ontology. "
msgstr "实体类 {} 不在本体中。"

#: /root/WorkCode/kweaver/builder/service/subgraph_service.py:54
#: /root/WorkCode/kweaver/builder/service/subgraph_service.py:120
msgid "edge {} not in the ontology. "
msgstr "边类 {} 不在本体中。"

#: /root/WorkCode/kweaver/builder/service/subgraph_service.py:122
msgid "subgraph id {} has unexpected classes: "
msgstr "子图 {} 有实体类或边类不在本体中："

#: /root/WorkCode/kweaver/builder/utils/celery_check_params_json.py:188
#, fuzzy
msgid "subgraph_ids cannot be empty."
msgstr "subgraph_ids不能为空。"

#: /root/WorkCode/kweaver/builder/utils/celery_check_params_json.py:192
#, fuzzy
msgid "subgraph_ids must be a list."
msgstr "subgraph_ids 必须为列表。"

#: /root/WorkCode/kweaver/builder/utils/celery_check_params_json.py:196
#, fuzzy
msgid "subgraph_ids have repeating items."
msgstr "subgraph_ids 有重复项。"

#: /root/WorkCode/kweaver/builder/utils/celery_check_params_json.py:202
#, fuzzy
msgid "subgraph_id must be int and must be larger than zero."
msgstr "subgraph_id必须大于0."

#: /root/WorkCode/kweaver/builder/utils/celery_check_params_json.py:208
#, fuzzy
msgid "write_mode cannot be empty."
msgstr "参数 name 不能为空。"

#: /root/WorkCode/kweaver/builder/utils/celery_check_params_json.py:212
msgid "write_mode must be skip or overwrite."
msgstr "write_mode必须为skip或overwrite。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:102
#, fuzzy, python-format
msgid "parameters: %s can not be empty!"
msgstr "参数 %s 不能为空。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:113
#, fuzzy
msgid "parameters: page must be int, and more than zero!"
msgstr "参数 graph_id 必须大于0."

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:117
#, fuzzy
msgid "parameters: order must be asc or desc!"
msgstr "参数 return_all 只能为 False 或 True。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:121
msgid ""
"parameters: status must be in (normal, running, waiting, failed, stop, "
"all)!"
msgstr "参数 status 只能为 (normal, running, waiting, failed, stop, all) 之一。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:125
#, fuzzy
msgid "parameters: graph_name Length over 50."
msgstr "graph_id必须为正整数"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:129
#, fuzzy
msgid "parameters: size must be int, and more than zero!"
msgstr "参数 subgraph_id 必须大于0."

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:133
#, fuzzy
msgid "parameters: tas_type must be in (full,increment,all)"
msgstr "参数 task_ids 的内容必须为整数。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:137
#, fuzzy
msgid "parameters: trigger_type must be in (0,1,2,all)"
msgstr "参数 graph_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:146
#, fuzzy, python-format
msgid "parameters: %s error!"
msgstr "参数 %s 错误"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:148
#, fuzzy, python-format
msgid "parameters: %s illegal!"
msgstr "参数：%s 缺失！"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:150
#, fuzzy, python-format
msgid "parameters: %s no rule!"
msgstr "参数 %s 不能为空。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:152
msgid "unknown error!"
msgstr "未知错误！"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:1197
#, python-format
msgid "parameters:  %s  are not required!,"
msgstr "参数：%s 不需要！"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:1200
#, python-format
msgid "parameters:  %s  are Missing!,"
msgstr "参数：%s 缺失！"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:1206
msgid "parameters task_id must be list!"
msgstr "task_id必须为列表"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:1212
msgid "parameters: task_ids content must be int."
msgstr "参数 task_ids 的内容必须为整数。"

#: /root/WorkCode/kweaver/builder/utils/ds_check_parameters.py:1215
msgid "parameters: task_ids list can not be empty."
msgstr "参数 task_ids 列表不能为空。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1805
#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1931
msgid "parameter name cannot be empty. "
msgstr "参数 name 不能为空。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1809
msgid ""
"parameter name cannot exceed 50 characters and characters must be "
"numbers, _, chinese or english. "
msgstr "参数 name 不能超过50个字符且只能由数字、下划线、中文和英文组成。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1813
msgid "parameter name cannot be \"未分组\" or \"ungrouped\". "
msgstr "参数 name 不能为 未分组 或 ungrouped."

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1819
#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:2010
msgid "parameter graph_id cannot be empty."
msgstr "参数 graph_id 不能为空。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1823
#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:2014
msgid "parameter graph_id must be int. "
msgstr "graph_id必须为正整数"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1827
#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:2018
msgid "parameter graph_id must be larger than zero."
msgstr "参数 graph_id 必须大于0."

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1833
msgid "parameter ontology_id cannot be empty."
msgstr "参数 ontology_id 不能为空。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1837
msgid "parameter ontology_id must be int. "
msgstr "参数 ontology_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1841
msgid "parameter ontology_id must be larger than zero."
msgstr "参数 ontology_id 必须大于0."

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1902
msgid "the parameter must be a list. "
msgstr "参数 必须为列表。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1911
msgid "parameter subgraph_id cannot be empty."
msgstr "subgraph_id不能为空"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1915
msgid "parameter subgraph_id must be int. "
msgstr "参数 subgraph_id 必须为整数。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1919
msgid "parameter subgraph_id must be larger than zero."
msgstr "参数 subgraph_id 必须大于0."

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1923
msgid "subgraph id {} is duplicate. "
msgstr "子图id {} 重复。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1935
msgid ""
"parameter name {} cannot exceed 50 characters and characters must be "
"numbers, _, chinese or english. "
msgstr "参数 name {} 不能超过50个字符且只能由数字、下划线、中文和英文组成。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1942
msgid "name {} is duplicate."
msgstr "名称 {} 重复。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1950
msgid "parameter entity must be list. "
msgstr "参数 entity 必须为列表。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:1975
msgid "parameter edge must be list. "
msgstr "参数 edge 必须为列表。"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:2024
msgid "parameter subgraph_name cannot be empty."
msgstr "subgraph_name不能为空"

#: /root/WorkCode/kweaver/builder/utils/graph_check_parameters.py:2030
msgid "parameter return_all must be False or True."
msgstr "参数 return_all 只能为 False 或 True。"

#~ msgid "File format conflict, all file structures need to be unified."
#~ msgstr "字段格式冲突，所有文件的内容结构需要一致"

#~ msgid "The file format only supports CSV and TXT."
#~ msgstr "上传文件仅支持csv和txt."

#~ msgid "The maximum number of uploaded file is 5;"
#~ msgstr "上传文件个数最多为5个."

#~ msgid "Failed to get file."
#~ msgstr "获取文件失败"

#~ msgid "Please check graph build status"
#~ msgstr "请检查图谱构建状态"

#~ msgid "parameter [arg] error"
#~ msgstr "参数 [arg] 错误"

#~ msgid "[class_type] [class_name] is not in ontology."
#~ msgstr "[class_type] [class_name] 不在本体中."

#~ msgid "[class_type] [class_name]  is not in ontology."
#~ msgstr "[class_type] [class_name] 不在本体中."

#~ msgid "caution! task not exists. "
#~ msgstr "graphid [graphid] 不存在"

#~ msgid "parameters:  %s  error!"
#~ msgstr "参数错误"

#~ msgid "parameters: %s no rule!"
#~ msgstr "参数错误"

#~ msgid "parameters: %s can not be empty !,"
#~ msgstr "参数 %s 不能为空"

